# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\haitong\VehicleTracking\code\qt\ui\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1242, 966)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 1181, 911))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_2.addWidget(self.groupBox_7, 1, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_4)
        self.textBrowser_2.setGeometry(QtCore.QRect(40, 20, 481, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox_4)
        self.graphicsView_2.setGeometry(QtCore.QRect(40, 70, 481, 281))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.groupBox_4)
        self.openGLWidget.setGeometry(QtCore.QRect(100, 90, 371, 231))
        self.openGLWidget.setObjectName("openGLWidget")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setGeometry(QtCore.QRect(470, 360, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit.setGeometry(QtCore.QRect(40, 360, 411, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 400, 411, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 400, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_2.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_5)
        self.textBrowser.setGeometry(QtCore.QRect(30, 30, 481, 61))
        self.textBrowser.setObjectName("textBrowser")
        self.openGLWidget_2 = QtWidgets.QOpenGLWidget(self.groupBox_5)
        self.openGLWidget_2.setGeometry(QtCore.QRect(30, 130, 421, 281))
        self.openGLWidget_2.setObjectName("openGLWidget_2")
        self.gridLayout_2.addWidget(self.groupBox_5, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1242, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_7.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton.setText(_translate("MainWindow", "Load Video"))
        self.pushButton_2.setText(_translate("MainWindow", "Set Relus"))
        self.groupBox_6.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox"))
